### ISSUE TITLE
How to define datasource besides H2?

### ISSUE THREAD

**Issue by mallim** [igormukhin/spring-boot-sample-data-eclipselink-war#1]
Hi 

this is a good example on using eclipselink.

May I know how you manage to define other datasources besides H2?

Thanks
Ian Lim

**Comment by igormukhin** [comment]
Ian, see [Working with SQL databases](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html) in Spring Boot documentation.
